create table if not exists public.lotly_transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('buy', 'sell')),
  item_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price_cents integer not null check (unit_price_cents > 0),
  transaction_date date not null,
  source text not null check (source in ('eBay', 'Vinted', 'Other')),
  category text not null check (category in ('Cloth', 'Bag', 'Watch')),
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.lotly_inventory_statuses (
  item_key text primary key,
  status text not null check (status in ('In stock', 'Listed', 'On hold', 'Sold', 'Returned')),
  updated_at timestamptz not null default now()
);

alter table public.lotly_transactions enable row level security;
alter table public.lotly_inventory_statuses enable row level security;
